In [15]:
import pandas as pd

constellation = pd.read_csv('constellation_catalog.csv')

display(constellation)

,source_image,constellation_id,num_stars,centroid_x,centroid_y,avg_brightness,bbox,star_coordinates,full_data
0,resized_image.jpg,resized_image_const_0,15,121.066667,138.666667,161.201815,"(np.int64(21), np.int64(8), np.int64(239), np....","[(21, 248), (32, 232), (239, 227), (117, 216),...","{'id': np.int64(0), 'num_stars': 15, 'stars': ..."
1,space.jpg,space_const_3,289,2232.145329,2817.923875,138.129897,"(np.int64(1255), np.int64(1224), np.int64(3404...","[(1750, 4589), (1632, 4504), (1466, 4451), (19...","{'id': np.int64(3), 'num_stars': 289, 'stars':..."
2,space.jpg,space_const_28,91,3804.000000,1215.538462,138.453109,"(np.int64(3046), np.int64(708), np.int64(4527)...","[(4144, 2049), (4118, 1978), (4191, 1875), (39...","{'id': np.int64(28), 'num_stars': 91, 'stars':..."
3,space.jpg,space_const_22,84,583.559524,1935.547619,135.535520,"(np.int64(4), np.int64(1199), np.int64(1157), ...","[(1015, 2925), (955, 2811), (834, 2767), (921,...","{'id': np.int64(22), 'num_stars': 84, 'stars':..."
4,space.jpg,space_const_30,29,1305.689655,1420.896552,142.793561,"(np.int64(952), np.int64(1189), np.int64(1570)...","[(1204, 1849), (1141, 1726), (1177, 1657), (13...","{'id': np.int64(30), 'num_stars': 29, 'stars':..."
...,...,...,...,...,...,...,...,...,...
63,image0.jpg,image0_const_0,33,391.272727,1177.909091,184.213519,"(np.int64(145), np.int64(950), np.int64(531), ...","[(280, 1361), (172, 1343), (251, 1339), (305, ...","{'id': np.int64(0), 'num_stars': 33, 'stars': ..."
64,image0.jpg,image0_const_2,33,885.757576,819.454545,186.441303,"(np.int64(756), np.int64(663), np.int64(1071),...","[(787, 950), (797, 948), (776, 947), (767, 941...","{'id': np.int64(2), 'num_stars': 33, 'stars': ..."
65,image0.jpg,image0_const_4,13,478.307692,538.846154,187.260637,"(np.int64(414), np.int64(483), np.int64(528), ...","[(447, 611), (436, 611), (469, 586), (430, 576...","{'id': np.int64(4), 'num_stars': 13, 'stars': ..."
66,image0.jpg,image0_const_3,9,243.555556,705.000000,184.514065,"(np.int64(220), np.int64(668), np.int64(271), ...","[(246, 724), (255, 722), (235, 721), (226, 715...","{'id': np.int64(3), 'num_stars': 9, 'stars': [..."
67,image0.jpg,image0_const_1,5,767.200000,1202.000000,183.424980,"(np.int64(755), np.int64(1169), np.int64(790),...","[(769, 1223), (758, 1223), (755, 1203), (790, ...","{'id': np.int64(1), 'num_stars': 5, 'stars': [..."